apiVersion: operator.cryostat.io/v1beta1
kind: Cryostat
metadata:

  finalizers:
    - operator.cryostat.io/cryostat.finalizer

  name: cryostat-sample
spec:
  enableCertManager: false
  minimal: false
  reportOptions:
    resources: {}
  resources:
    coreResources: {}
    dataSourceResources: {}
    grafanaResources:
      limits:
        cpu: '1'
  storageOptions:
    pvc:
      spec:
        resources: {}

